# Generated by Django 4.0.2 on 2022-03-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
